### ISSUE TITLE
GP : labels pour les issues

### ISSUE THREAD

**Issue by storm1er** [Shikatamo/OGE#12]
# Labels proposé :

Un seul label possible par issue

## Pour le projet : 

- [x] Web/Feature - _Nouvelle fonctionnalités_
- [x] Web/Enhancement - _Amélioration d'une fonctionnalité existante_
- [x] Web/Fix - _Bug d'une fonctionnalités_
- [x] Web/Contrib - _Problème de contribution user avec une fonctionnalités_

Il est possible qu'une issue change de label

## Pour la doc :

- [x] Wiki/Page - _Concerne une seule et unique page du wiki_
- [x] Wiki/Doc - _Concerne l'organisation, la présentation sur la globalité du wiki_
- [x] Wiki/Oops - _Concerne les 'fix' d'orthographe, grammaire, fautes de frappe dans le wiki_

**Comment by Shikatamo** [comment]
J'ai modifié les issues que j'avais enregistrées

**Comment by storm1er** [comment]
Fail : https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/

Tu connais du tout github ? ^^'

**Comment by storm1er** [comment]
Ajout d'un label `Web/Git` pour la gestion du git, visiblement on va en avoir besoin ;)
