### ISSUE TITLE
GP : template pour les issues

### ISSUE THREAD

**Issue by storm1er** [Shikatamo/OGE#13]
# Pour les labels `Web/Feature` et `Web/Enhancement` :  

_c.f. #12_

> ## Quoi :  
> _Texte, mail, message provenant de l'asso, d'un adhérent ou autre_
> 
> ## Transformation :  
> ### Faisabilité / Spec complète : 
> - [ ] OK - _Description complète et faisable_
> - [ ] NOK - _Description incomplète, besoin de renseignement suplémentaire ou faisabilité incertaine_
> - [ ] KO - _Infaisable en l'état, besoin de spec particulière_
> 
> ### Description / Spec : 
> _Détail sur le *comment* se sera fait et avec quels outils / framework / plugin / ... selon la base du projet_
>
> - [ ] La page du wiki existent pour cette issue : #[Issue `Wiki/Page`]
> - [ ] Il faut compléter la wiki pour cette issue : #[Issue `Wiki/Page`]
> - [ ] Ceci est un `Web/Enhancement` : #[Issue `Web/Feature` qui correspond]
> 
> ### User Story : 
> - En tant que [Role] je peux [Action]
> - ...
> 

# Pour les labels `Web/Fix` et `Web/Contrib` :  

> ## Quoi :  
> _Texte, mail, message provenant de l'asso, d'un adhérent ou autre_
> 
> ## Description technique : 
> _Détails techniques de la correction à appliquer, log, ..._
>
> - [ ] Bug reproductible : [Lien vers le bug reproduit : image, paste.bin de log, ...](url)
> - [ ] #[Issue `Web/Feature` qui correspond]

# Pour les labels `Wiki/Doc` et `Wiki/Oops` :  

> ## Quoi :  
> _Texte, mail, message provenant de l'asso, d'un adhérent ou autre_
> 
> ## Description technique : 
> _Détails de la correction_
>
> - [ ] #[Issue `Wiki/Page` qui correspond]
> - [ ] #[Issue `Wiki/Page` qui correspond]
> - [ ] #[Issue `Wiki/Page` qui correspond]
> - [ ] #[Issue `Wiki/Page` qui correspond]
> - [ ] #[Issue `Wiki/Page` qui correspond]
> - [ ] #[Issue `Wiki/Page` qui correspond]
> - [ ] #[Issue `Wiki/Page` qui correspond]

**Comment by storm1er** [comment]
@Shikatamo je m'en occupe :) 
https://help.github.com/articles/creating-an-issue-template-for-your-repository/

**Comment by Shikatamo** [comment]
Welp, j'ai jamais utilisé Git comme outil de gestion de projet, du coup toute cette partie là est encore un peu obscure pour moi 😅

**Comment by storm1er** [comment]
Ça marche, je ferai l'effort d'envoyer la doc à chaque fois que ce sera possible ;)

Je viens de mettre le template en place. Quand tu fait "new issue" la description est pré-rempli. On a juste à garder/compléter la partie qui nous intéresse :)
