### ISSUE TITLE
Guideline pour le wiki

### ISSUE THREAD

**Issue by storm1er** [Shikatamo/OGE#19]
## Quoi :  
Guideline pour le wiki ...
Définir si le wiki Github est suffisant.

## Description technique : 
Trois pages principales : **Spécifications techniques**, **Contribution user** et **WorkFlow**.
### 1. Spécifications techniques : 
Page simple expliquant les technologies choisies.  
Avec les liens vers les docs officiels de chacune et "Pourquoi celles-ci" pour éviter de changer en cours de route, ou justement de justifier un changement.

### 2. Contribution user : 
Page contenant la liste de toutes les features.
#### Feature : 
- Une feature = Une page wiki (plusieurs possible selon le contexte)
- Qui "Suis-je" (visiteur, membre, droit necessaire, ...)
- But de la feature
- Action à mener pour arriver au but (_où, quand, comment, ..._)

### 3. WorkFlow : 
Page contenant la liste de toutes les méthodes pour le développement du projet.
#### Méthode (à faire / compléter) : 
- Toute tache automatisé (`grunt`, `travis`, `jasmine`, ...) doit faire l'objet d'une page wiki
*Ce serai con de ne plus se souvenir ce que fait `cmd machin` pour la v2.0*
- Contribuer sur Github
- Pages de coding standard
- Pipeline de MEP

**Comment by storm1er** [comment]
@Shikatamo Tu confirmes ?

Dès que ce sera ok, j'ouvrirai les issues pour les premières pages et on commencera à débattre des techno, etc ... (après là première réunion avec l'asso j'espère)

**Comment by Shikatamo** [comment]
Ça roule je vois pas trop quoi ajouter ça a l'air assez exhaustif

**Comment by storm1er** [comment]
Création de l'accueil
https://github.com/Shikatamo/OGE/wiki

**Comment by storm1er** [comment]
Cette issue va probablement se transformer en page wiki d'ailleurs : 
- Chaque page wiki devra cité en début de page un breadcrumb complet avec les pages inférieur jusqu'à l'accueil
- Chaque page wiki devra cité en fin de page l'issue qui lui correspond
- Chaque page wiki devra contenir au moins un titre principale et une description

```
[Accueil](https://github.com/Shikatamo/OGE/wiki) > [Titre](lien page wiki)
----
# Titre
_Description_
[...]
----
[#__](lien issue de la page)
```

**Comment by storm1er** [comment]
Page du wiki : https://github.com/Shikatamo/OGE/wiki/Guideline-du-Wiki
