### ISSUE TITLE
Spécifications techniques

### ISSUE THREAD

**Issue by storm1er** [Shikatamo/OGE#20]
## Quoi :  
Issue débat pour les spec' techniques de bases.  
Cf #19, permettra l'ouverture des pages wiki principales.

## Description technique : 
À définir : 
- [X] Langage : [_React_](https://facebook.github.io/react/)
- [X] Coding standard : [_Coding standard d'airBnb_](https://github.com/airbnb/javascript/tree/master/react)
- [X] Hébergement : [_Firebase_](https://firebase.google.com/)
- [X] DB : [_Firebase_](https://firebase.google.com/)

**Comment by storm1er** [comment]
## Proposition de boilerplate complet : 

- Langage : React
- Hebergement : Firebase
- DB : Firebase

<details>

En utilisant le boilerplate [facebookincubator/create-react-app](https://github.com/facebookincubator/create-react-app)
- Focus sur le code et pas la gestion de projet (grunt, automatisation, ...)
- [PWA ready](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#making-a-progressive-web-app)
- [Contient de quoi gérer les test unitaires (histoire qu'on ai la paix à chaque nouvelle feature)](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#running-tests)
- [Contient déjà différentes solution d’hébergements gratuit, DB incluse](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment)
- [Permet de coder en composant et pas en héritage (réutilisation et développement parallèle en évitant les conflits)](https://facebook.github.io/react/docs/composition-vs-inheritance.html)
=> [Donc du coup un coding standard déjà prêt](https://facebook.github.io/react/contributing/design-principles.html)
- [Pré-intégration de builder pour une integration continue](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#travis-ci)

### Pour : 
- Ça fait le café :coffee: (serveur, test, plus besoin de s'installer un _amp ou autre)
- Pure front, donc pas de gestion serveur compliqué
- C'est nouveau, c'est fun, ça s'apprend vite :100: 

### Contre : 
- Base de données particulière (Firebase, lowDB, pouchDB, ...)

### IMO : 
Pour ce que j'ai manipulé React : 
- Je le trouve beaucoup plus simple que angular ou vue.js
- Grande communauté, beaucoup de composants/plugins/snippet déjà fait
</details>

**Comment by storm1er** [comment]
@Shikatamo Dit moi ce que tu en penses quand tu pourras =)

**Comment by Shikatamo** [comment]
Le react j'en ai fait qu'une fois, je me rappelle pas avoir super accroché avec le système mixte html/js mais c'est plutôt sympa comme techno alors pourquoi pas. 

J'ai beaucoup plus bossé avec de l'angular 1, du coup de toutes façons qu'on passe sur react, vue ou angular 4 j'aurais des trucs à apprendre. Je te fais confiance sur le coup.

Firebase ça marche pas trop mal, par contre y'a moyen d'avoir une base indépendante sur Firebase ? Si on se met à stocker des données sensibles y'aura pas un problème niveau sécurité/loi ?

Maintenant effectivement ça nous permet d'avoir une structure très légère, mais si on pars sur des évolutions plus grosses dans le futur on sera un peu largué non ? Si on veut un truc qu'on puisse modifier en profondeur faudrait partir sur un truc plus lourd genre un Spring (y'a Java 9 qui arrive là) ou un Synfony 4 (la version stable sort en novembre). Mais ça rends ça beaucoup plus lourd effectivement, faudra qu'on voit après la première réunion vers quoi on se dirige.

**Comment by storm1er** [comment]
### TL;DR
@Shikatamo 
- Tu connais pas du tout les version ultérieur d'angular ? Tu penses que ça vaux le coup de chercher ?
- Non, Firebase et Cnil n'est pas un mélange illégale.
- Pour le fait d'être coincé en évolution par React : voir plus bas
> _Facebook repose sur React depuis quelques temps maintenant ... je pense pas que "évolutions plus grosses" inclu "gérer l'équivalent d'un reseaux social internationnal" xD_
- Tu penses qu'on fera du gros dev pour OGE ? J'espérais rester sur de la micro-feature.
*La réunion avec l'asso confirmera oui ou non de toute façon ...*

<details>

>Le react j'en ai fait qu'une fois, je me rappelle pas avoir super accroché avec le système mixte html/js mais c'est plutôt sympa comme techno alors pourquoi pas. 
>
>J'ai beaucoup plus bossé avec de l'angular 1, du coup de toutes façons qu'on passe sur react, vue ou angular 4 j'aurais des trucs à apprendre. Je te fais confiance sur le coup.

J'ai très mal vécu angular 1 ... mais du coup je connais pas les version ultérieur, y parrait que c'est complètement différent donc à voir.
>Firebase ça marche pas trop mal, par contre y'a moyen d'avoir une base indépendante sur Firebase ? Si on se met à stocker des données sensibles y'aura pas un problème niveau sécurité/loi ?

Apparement non, on serait pas les seul à le faire : http://www.talir.me/politique-de-donnees/
*(un exemple parmis d'autre, "Firebase Cnil" dans google donne une pelleté de résultat)*
>Maintenant effectivement ça nous permet d'avoir une structure très légère, mais si on pars sur des évolutions plus grosses dans le futur on sera un peu largué non ?

Facebook.com repose sur React depuis quelques temps maintenant ... je pense pas que "évolutions plus grosses" inclu "gérer l'équivalent d'un reseaux social internationnal" xD  
Plus sérieusement : 
- Langage : on peux récupérer la main facilement, [create-react-app nous le permet](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-eject).   
- Hébergement : Firebase n'étant qu'un "dépot" de fichier, on pourras pas passer sur un langage server-side sans partir de Firebase.
- DB : Firebase bah ... c'est Firebase quoi, donc si on part bah on l'a plus ...
Si on change pour un autre type de DB front, c'est bon. Mais si c'est server-side il nous faudra récupérer la DB *(oui c'est possible)* et l'importer dans un nouveau serveur.

>Si on veut un truc qu'on puisse modifier en profondeur faudrait partir sur un truc plus lourd genre un Spring (y'a Java 9 qui arrive là) ou un Synfony 4 (la version stable sort en novembre). Mais ça rends ça beaucoup plus lourd effectivement, faudra qu'on voit après la première réunion vers quoi on se dirige.

C'est justement la problèmatique ici : il nous faut un développement le plus léger possible, si on travail qu'une heure par semaine, ça va vite prendre du plomb dans l'aile avec Symfony, Wordpress, Drupal ou même Spring *(comme avec n'importe quelle langage serveur en fait ...)*.
</details>

**Comment by storm1er** [comment]
Si react est validé : [Coding standard d'airBnb](https://github.com/airbnb/javascript/tree/master/react)

Liste simple à comprendre où chaque règles est expliqué. Il faut confirmer que c'est applicable à create-react-app (composants ?)

**Comment by Shikatamo** [comment]
@storm1er 

Pour les nouvelles version d'angular je les ai vue passer rapidos. Mais je pense pas qu'elles soient spécialement plus adaptées que React pour le projet. J'aime juste mieux le modèle MVC d'Angular que ce que propose React, mais ça me fera pas de mal de diversifier un peu !

Les guidelines semblent bonne j'ai parcouru vite fait, si jamais ça coince pour certaine de nos applications on s'adaptera en les gardant comme base, du moment qu'on est clair dans la doc quand on en met une nouvelle en place ça devrait pas poser de problèmes.

Et ouais, pour sortir le site qu'ils veulent aujourd'hui on devrait pas avoir besoin de gros gros dev, par contre c'est toujours plus sympa d'avoir la main mise sur l'intégralité du projet "au cas ou". Parce que le jour ou ça sera repris par quelqu'un d'autre il risque d'avoir pas mal de taf si il veut tout rapatrier. Après si tu me dis qu'une transition de Firebase vers une base de donnée perso c'est pas infaisable le jour où on en a besoin on pourra se build un backend digne de ce nom, mais effectivement si on veut pas y passer des heures c'est plus simple comme ça.

**Comment by storm1er** [comment]
@Shikatamo 
>Pour les nouvelles version d'angular je les ai vue passer rapidos. Mais je pense pas qu'elles soient spécialement plus adaptées que React pour le projet. J'aime juste mieux le modèle MVC d'Angular que ce que propose React, mais ça me fera pas de mal de diversifier un peu !

Bon, pour le moment on se dirige vers React, ok.
>Les guidelines semblent bonne j'ai parcouru vite fait, si jamais ça coince pour certaine de nos applications on s'adaptera en les gardant comme base, du moment qu'on est clair dans la doc quand on en met une nouvelle en place ça devrait pas poser de problèmes.

Le but c'est justement de s'y tenir, comme ça on gagne du temps et on sait ou chercher ... sinon ça va être la misère.
>Et ouais, pour sortir le site qu'ils veulent aujourd'hui on devrait pas avoir besoin de gros gros dev, par contre c'est toujours plus sympa d'avoir la main mise sur l'intégralité du projet "au cas ou". Parce que le jour ou ça sera repris par quelqu'un d'autre il risque d'avoir pas mal de taf si il veut tout rapatrier. Après si tu me dis qu'une transition de Firebase vers une base de donnée perso c'est pas infaisable le jour où on en a besoin on pourra se build un backend digne de ce nom, mais effectivement si on veut pas y passer des heures c'est plus simple comme ça.

Un *backend digne de ce nom* ? cad ?

**Comment by storm1er** [comment]
Voir les issues correspondant à chaque éléments pour la suite.

**Comment by storm1er** [comment]
page Wiki ajouté https://github.com/Shikatamo/OGE/wiki/Sp%C3%A9cifications-techniques
