### ISSUE TITLE
Déscription des pratiques - Ecole d'escrime

### ISSUE THREAD

**Issue by Shikatamo** [Shikatamo/OGE#4]
## Quoi :  
Mail de Laure Bonnefond : 
> Détail des pratiques 
          Loisirs : quel public concerné
          Ecole d’escrime
          Compétiteurs
          Baby escrime
          Fitness

 ## Transformation :  
 ### Faisabilité / Spec complète : 
 - [ ] OK - _Description complète et faisable_
 - [ ] NOK - _Description incomplète, besoin de renseignement suplémentaire ou faisabilité incertaine_
 - [x] KO - _Infaisable en l'état, besoin de spec particulière_
 
 ### Description / Spec : 

 - [ ] La page du wiki existent pour cette issue : #[Issue `Wiki/Page`]
 - [x] Il faut compléter la wiki pour cette issue : #[Issue `Wiki/Page`]
 - [ ] Ceci est un `Web/Enhancement` : #[Issue `Web/Feature` qui correspond]
 
 ### User Story : 
 - En tant que visiteur je peux voir une description des pratiques/objectifs de l'école d'escrime

**Comment by Shikatamo** [comment]
Grouped at [#4](https://github.com/Shikatamo/OGE/issues/14)

**Comment by storm1er** [comment]
Duplicate of #14
